services:
  authentication_service:
    build:
      context: ./authenticationService
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped

  drivermatching_service:
    build:
      context: ./driverMatchingService
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    restart: unless-stopped

  tripmanagement_service:
    build:
      context: ./tripManagementService
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    restart: unless-stopped

  location_service:
    build:
      context: ./locationService
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    restart: unless-stopped

  notification_service:
    build:
      context: ./notificationService
      dockerfile: Dockerfile
    ports:
      - "8005:8005"
    restart: unless-stopped