"""New migration

Revision ID: d88132c26c13
Revises: 
Create Date: 2024-10-22 02:09:49.242103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'd88132c26c13'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='genderenum'), nullable=False),
    sa.Column('home_address', sa.String(length=255), nullable=True),
    sa.Column('home_location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_customer_home_location', 'customer', ['home_location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_customer_id'), 'customer', ['id'], unique=True)
    op.create_table('driver',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='genderenum'), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('rating_nos', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_id'), 'driver', ['id'], unique=True)
    op.create_table('vehicle',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=False),
    sa.Column('registration_number', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type', sa.Enum('BIKE', 'MOTORBIKE', 'SCOOTER', 'CAR', 'MINI_TRUCK', 'PICKUP_TRUCK', 'LORRY', 'TRAILER', 'VAN', 'CONTAINER_TRUCK', 'REFRIGERATED_TRUCK', name='vehicletype'), nullable=False),
    sa.Column('capacity', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_id'), 'vehicle', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_id'), table_name='vehicle')
    op.drop_table('vehicle')
    op.drop_index(op.f('ix_driver_id'), table_name='driver')
    op.drop_table('driver')
    op.drop_index(op.f('ix_customer_id'), table_name='customer')
    op.drop_index('idx_customer_home_location', table_name='customer', postgresql_using='gist')
    op.drop_table('customer')
    # ### end Alembic commands ###
